manifest:
  remotes:
    - name: upstream
      url: https://github.com/zmkfirmware/zmk
  repositories:
    - name: zmk
      remote: upstream
      revision: main
    - name: zmk-config-romergo
      path: zmk-config-romergo
      revision: main